version: '3'
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/discord-bot
    ports:
      - '3000:3000'
    image: discord-bot
    env_file:
      - docker.env
